// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: bot-manager.proto

package bot_manager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendBotCommandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId int32  `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Command  string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
}

func (x *SendBotCommandRequest) Reset() {
	*x = SendBotCommandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bot_manager_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendBotCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBotCommandRequest) ProtoMessage() {}

func (x *SendBotCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_manager_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBotCommandRequest.ProtoReflect.Descriptor instead.
func (*SendBotCommandRequest) Descriptor() ([]byte, []int) {
	return file_bot_manager_proto_rawDescGZIP(), []int{0}
}

func (x *SendBotCommandRequest) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *SendBotCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type SendBotCommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommandId string `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Success   bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *SendBotCommandResponse) Reset() {
	*x = SendBotCommandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bot_manager_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendBotCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBotCommandResponse) ProtoMessage() {}

func (x *SendBotCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_manager_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBotCommandResponse.ProtoReflect.Descriptor instead.
func (*SendBotCommandResponse) Descriptor() ([]byte, []int) {
	return file_bot_manager_proto_rawDescGZIP(), []int{1}
}

func (x *SendBotCommandResponse) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *SendBotCommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SendBotCommandV2Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId int32  `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Command  string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
}

func (x *SendBotCommandV2Request) Reset() {
	*x = SendBotCommandV2Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bot_manager_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendBotCommandV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBotCommandV2Request) ProtoMessage() {}

func (x *SendBotCommandV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_bot_manager_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBotCommandV2Request.ProtoReflect.Descriptor instead.
func (*SendBotCommandV2Request) Descriptor() ([]byte, []int) {
	return file_bot_manager_proto_rawDescGZIP(), []int{2}
}

func (x *SendBotCommandV2Request) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *SendBotCommandV2Request) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type SendBotCommandV2Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommandId       string  `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	SuccessCommand  bool    `protobuf:"varint,2,opt,name=success_command,json=successCommand,proto3" json:"success_command,omitempty"`
	SuccessGarant   bool    `protobuf:"varint,3,opt,name=success_garant,json=successGarant,proto3" json:"success_garant,omitempty"`
	CommandRequest  string  `protobuf:"bytes,4,opt,name=command_request,json=commandRequest,proto3" json:"command_request,omitempty"`
	CommandResponse string  `protobuf:"bytes,5,opt,name=command_response,json=commandResponse,proto3" json:"command_response,omitempty"`
	Error           *string `protobuf:"bytes,6,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *SendBotCommandV2Response) Reset() {
	*x = SendBotCommandV2Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bot_manager_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendBotCommandV2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBotCommandV2Response) ProtoMessage() {}

func (x *SendBotCommandV2Response) ProtoReflect() protoreflect.Message {
	mi := &file_bot_manager_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBotCommandV2Response.ProtoReflect.Descriptor instead.
func (*SendBotCommandV2Response) Descriptor() ([]byte, []int) {
	return file_bot_manager_proto_rawDescGZIP(), []int{3}
}

func (x *SendBotCommandV2Response) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *SendBotCommandV2Response) GetSuccessCommand() bool {
	if x != nil {
		return x.SuccessCommand
	}
	return false
}

func (x *SendBotCommandV2Response) GetSuccessGarant() bool {
	if x != nil {
		return x.SuccessGarant
	}
	return false
}

func (x *SendBotCommandV2Response) GetCommandRequest() string {
	if x != nil {
		return x.CommandRequest
	}
	return ""
}

func (x *SendBotCommandV2Response) GetCommandResponse() string {
	if x != nil {
		return x.CommandResponse
	}
	return ""
}

func (x *SendBotCommandV2Response) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type BotGetOnlineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId int32  `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
}

func (x *BotGetOnlineRequest) Reset() {
	*x = BotGetOnlineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bot_manager_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotGetOnlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotGetOnlineRequest) ProtoMessage() {}

func (x *BotGetOnlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_manager_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotGetOnlineRequest.ProtoReflect.Descriptor instead.
func (*BotGetOnlineRequest) Descriptor() ([]byte, []int) {
	return file_bot_manager_proto_rawDescGZIP(), []int{4}
}

func (x *BotGetOnlineRequest) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *BotGetOnlineRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type BotGetOnlineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nickname string `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	RegIp    string `protobuf:"bytes,2,opt,name=reg_ip,json=regIp,proto3" json:"reg_ip,omitempty"`
	LastIp   string `protobuf:"bytes,3,opt,name=last_ip,json=lastIp,proto3" json:"last_ip,omitempty"`
}

func (x *BotGetOnlineResponse) Reset() {
	*x = BotGetOnlineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bot_manager_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotGetOnlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotGetOnlineResponse) ProtoMessage() {}

func (x *BotGetOnlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_manager_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotGetOnlineResponse.ProtoReflect.Descriptor instead.
func (*BotGetOnlineResponse) Descriptor() ([]byte, []int) {
	return file_bot_manager_proto_rawDescGZIP(), []int{5}
}

func (x *BotGetOnlineResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *BotGetOnlineResponse) GetRegIp() string {
	if x != nil {
		return x.RegIp
	}
	return ""
}

func (x *BotGetOnlineResponse) GetLastIp() string {
	if x != nil {
		return x.LastIp
	}
	return ""
}

type BotGetOrgMemberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId       int32 `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	OrganizationId int32 `protobuf:"varint,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
}

func (x *BotGetOrgMemberRequest) Reset() {
	*x = BotGetOrgMemberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bot_manager_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotGetOrgMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotGetOrgMemberRequest) ProtoMessage() {}

func (x *BotGetOrgMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_manager_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotGetOrgMemberRequest.ProtoReflect.Descriptor instead.
func (*BotGetOrgMemberRequest) Descriptor() ([]byte, []int) {
	return file_bot_manager_proto_rawDescGZIP(), []int{6}
}

func (x *BotGetOrgMemberRequest) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *BotGetOrgMemberRequest) GetOrganizationId() int32 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

type BotGetOrgMemberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrganizationId   int32  `protobuf:"varint,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	OrganizationName string `protobuf:"bytes,2,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	LeaderName       string `protobuf:"bytes,3,opt,name=leader_name,json=leaderName,proto3" json:"leader_name,omitempty"`
	LeaderId         int32  `protobuf:"varint,4,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	DeputyCount      int32  `protobuf:"varint,5,opt,name=deputy_count,json=deputyCount,proto3" json:"deputy_count,omitempty"`
	MemberCount      int32  `protobuf:"varint,6,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	MemberAfkCount   int32  `protobuf:"varint,7,opt,name=member_afk_count,json=memberAfkCount,proto3" json:"member_afk_count,omitempty"`
	Raw              string `protobuf:"bytes,8,opt,name=raw,proto3" json:"raw,omitempty"`
}

func (x *BotGetOrgMemberResponse) Reset() {
	*x = BotGetOrgMemberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bot_manager_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotGetOrgMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotGetOrgMemberResponse) ProtoMessage() {}

func (x *BotGetOrgMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_manager_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotGetOrgMemberResponse.ProtoReflect.Descriptor instead.
func (*BotGetOrgMemberResponse) Descriptor() ([]byte, []int) {
	return file_bot_manager_proto_rawDescGZIP(), []int{7}
}

func (x *BotGetOrgMemberResponse) GetOrganizationId() int32 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *BotGetOrgMemberResponse) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *BotGetOrgMemberResponse) GetLeaderName() string {
	if x != nil {
		return x.LeaderName
	}
	return ""
}

func (x *BotGetOrgMemberResponse) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *BotGetOrgMemberResponse) GetDeputyCount() int32 {
	if x != nil {
		return x.DeputyCount
	}
	return 0
}

func (x *BotGetOrgMemberResponse) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *BotGetOrgMemberResponse) GetMemberAfkCount() int32 {
	if x != nil {
		return x.MemberAfkCount
	}
	return 0
}

func (x *BotGetOrgMemberResponse) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

var File_bot_manager_proto protoreflect.FileDescriptor

var file_bot_manager_proto_rawDesc = []byte{
	0x0a, 0x11, 0x62, 0x6f, 0x74, 0x2d, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x4e, 0x0a, 0x15, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x74, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x22, 0x51, 0x0a, 0x16, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x74, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x50, 0x0a, 0x17, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f,
	0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x56, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x82, 0x02, 0x0a, 0x18, 0x53, 0x65, 0x6e,
	0x64, 0x42, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x56, 0x32, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x25, 0x0a,
	0x0e, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x67, 0x61, 0x72, 0x61, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x47, 0x61,
	0x72, 0x61, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a,
	0x10, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x4e, 0x0a,
	0x13, 0x42, 0x6f, 0x74, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x62, 0x0a,
	0x14, 0x42, 0x6f, 0x74, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x5f, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x72, 0x65, 0x67, 0x49, 0x70, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x61, 0x73, 0x74,
	0x5f, 0x69, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x61, 0x73, 0x74, 0x49,
	0x70, 0x22, 0x5e, 0x0a, 0x16, 0x42, 0x6f, 0x74, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x6f, 0x72, 0x67, 0x61,
	0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x22, 0xaf, 0x02, 0x0a, 0x17, 0x42, 0x6f, 0x74, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a,
	0x0f, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x11, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x65, 0x70, 0x75, 0x74, 0x79, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x64, 0x65, 0x70, 0x75, 0x74, 0x79, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x28, 0x0a, 0x10, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x5f, 0x61, 0x66, 0x6b, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x41, 0x66, 0x6b, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x61, 0x77, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x72, 0x61, 0x77, 0x32, 0x8f, 0x02, 0x0a, 0x0a, 0x42, 0x6f, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x12, 0x3e, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x12, 0x16, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x53, 0x65, 0x6e, 0x64,
	0x42, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x44, 0x0a, 0x0d, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x56, 0x32, 0x12, 0x18, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x74, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x56, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e,
	0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x56, 0x32,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x4f,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x14, 0x2e, 0x42, 0x6f, 0x74, 0x47, 0x65, 0x74, 0x4f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x42, 0x6f,
	0x74, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x41, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x17, 0x2e, 0x42, 0x6f, 0x74, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x42, 0x6f,
	0x74, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1a, 0x5a, 0x18, 0x62, 0x6f, 0x74, 0x2d, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x2f, 0x3b, 0x62, 0x6f, 0x74, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bot_manager_proto_rawDescOnce sync.Once
	file_bot_manager_proto_rawDescData = file_bot_manager_proto_rawDesc
)

func file_bot_manager_proto_rawDescGZIP() []byte {
	file_bot_manager_proto_rawDescOnce.Do(func() {
		file_bot_manager_proto_rawDescData = protoimpl.X.CompressGZIP(file_bot_manager_proto_rawDescData)
	})
	return file_bot_manager_proto_rawDescData
}

var file_bot_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_bot_manager_proto_goTypes = []interface{}{
	(*SendBotCommandRequest)(nil),    // 0: SendBotCommandRequest
	(*SendBotCommandResponse)(nil),   // 1: SendBotCommandResponse
	(*SendBotCommandV2Request)(nil),  // 2: SendBotCommandV2Request
	(*SendBotCommandV2Response)(nil), // 3: SendBotCommandV2Response
	(*BotGetOnlineRequest)(nil),      // 4: BotGetOnlineRequest
	(*BotGetOnlineResponse)(nil),     // 5: BotGetOnlineResponse
	(*BotGetOrgMemberRequest)(nil),   // 6: BotGetOrgMemberRequest
	(*BotGetOrgMemberResponse)(nil),  // 7: BotGetOrgMemberResponse
}
var file_bot_manager_proto_depIdxs = []int32{
	0, // 0: BotManager.SendCommand:input_type -> SendBotCommandRequest
	2, // 1: BotManager.SendCommandV2:input_type -> SendBotCommandV2Request
	4, // 2: BotManager.GetOnline:input_type -> BotGetOnlineRequest
	6, // 3: BotManager.GetOrgMember:input_type -> BotGetOrgMemberRequest
	1, // 4: BotManager.SendCommand:output_type -> SendBotCommandResponse
	3, // 5: BotManager.SendCommandV2:output_type -> SendBotCommandV2Response
	5, // 6: BotManager.GetOnline:output_type -> BotGetOnlineResponse
	7, // 7: BotManager.GetOrgMember:output_type -> BotGetOrgMemberResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bot_manager_proto_init() }
func file_bot_manager_proto_init() {
	if File_bot_manager_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bot_manager_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendBotCommandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bot_manager_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendBotCommandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bot_manager_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendBotCommandV2Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bot_manager_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendBotCommandV2Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bot_manager_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotGetOnlineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bot_manager_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotGetOnlineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bot_manager_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotGetOrgMemberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bot_manager_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotGetOrgMemberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_bot_manager_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bot_manager_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bot_manager_proto_goTypes,
		DependencyIndexes: file_bot_manager_proto_depIdxs,
		MessageInfos:      file_bot_manager_proto_msgTypes,
	}.Build()
	File_bot_manager_proto = out.File
	file_bot_manager_proto_rawDesc = nil
	file_bot_manager_proto_goTypes = nil
	file_bot_manager_proto_depIdxs = nil
}
