// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: bot-manager.proto

package bot_manager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BotGetOrgMembersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId int32 `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
}

func (x *BotGetOrgMembersRequest) Reset() {
	*x = BotGetOrgMembersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bot_manager_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotGetOrgMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotGetOrgMembersRequest) ProtoMessage() {}

func (x *BotGetOrgMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_manager_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotGetOrgMembersRequest.ProtoReflect.Descriptor instead.
func (*BotGetOrgMembersRequest) Descriptor() ([]byte, []int) {
	return file_bot_manager_proto_rawDescGZIP(), []int{0}
}

func (x *BotGetOrgMembersRequest) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

type BotGetOrgMembersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*BotGetOrgMembersItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Error *string                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *BotGetOrgMembersResponse) Reset() {
	*x = BotGetOrgMembersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bot_manager_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotGetOrgMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotGetOrgMembersResponse) ProtoMessage() {}

func (x *BotGetOrgMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_manager_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotGetOrgMembersResponse.ProtoReflect.Descriptor instead.
func (*BotGetOrgMembersResponse) Descriptor() ([]byte, []int) {
	return file_bot_manager_proto_rawDescGZIP(), []int{1}
}

func (x *BotGetOrgMembersResponse) GetItems() []*BotGetOrgMembersItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *BotGetOrgMembersResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type BotGetOrgMembersItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrganizationId   int32  `protobuf:"varint,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	OrganizationName string `protobuf:"bytes,2,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	LeaderName       string `protobuf:"bytes,3,opt,name=leader_name,json=leaderName,proto3" json:"leader_name,omitempty"`
	LeaderId         int32  `protobuf:"varint,4,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	DeputyCount      int32  `protobuf:"varint,5,opt,name=deputy_count,json=deputyCount,proto3" json:"deputy_count,omitempty"`
	MemberCount      int32  `protobuf:"varint,6,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	MemberAfkCount   int32  `protobuf:"varint,7,opt,name=member_afk_count,json=memberAfkCount,proto3" json:"member_afk_count,omitempty"`
	Raw              string `protobuf:"bytes,8,opt,name=raw,proto3" json:"raw,omitempty"`
}

func (x *BotGetOrgMembersItem) Reset() {
	*x = BotGetOrgMembersItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bot_manager_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotGetOrgMembersItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotGetOrgMembersItem) ProtoMessage() {}

func (x *BotGetOrgMembersItem) ProtoReflect() protoreflect.Message {
	mi := &file_bot_manager_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotGetOrgMembersItem.ProtoReflect.Descriptor instead.
func (*BotGetOrgMembersItem) Descriptor() ([]byte, []int) {
	return file_bot_manager_proto_rawDescGZIP(), []int{2}
}

func (x *BotGetOrgMembersItem) GetOrganizationId() int32 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *BotGetOrgMembersItem) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *BotGetOrgMembersItem) GetLeaderName() string {
	if x != nil {
		return x.LeaderName
	}
	return ""
}

func (x *BotGetOrgMembersItem) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *BotGetOrgMembersItem) GetDeputyCount() int32 {
	if x != nil {
		return x.DeputyCount
	}
	return 0
}

func (x *BotGetOrgMembersItem) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *BotGetOrgMembersItem) GetMemberAfkCount() int32 {
	if x != nil {
		return x.MemberAfkCount
	}
	return 0
}

func (x *BotGetOrgMembersItem) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

type BotGetIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId      int32  `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Identificator string `protobuf:"bytes,2,opt,name=identificator,proto3" json:"identificator,omitempty"`
}

func (x *BotGetIDRequest) Reset() {
	*x = BotGetIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bot_manager_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotGetIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotGetIDRequest) ProtoMessage() {}

func (x *BotGetIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_manager_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotGetIDRequest.ProtoReflect.Descriptor instead.
func (*BotGetIDRequest) Descriptor() ([]byte, []int) {
	return file_bot_manager_proto_rawDescGZIP(), []int{3}
}

func (x *BotGetIDRequest) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *BotGetIDRequest) GetIdentificator() string {
	if x != nil {
		return x.Identificator
	}
	return ""
}

type BotGetIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname   string  `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Level      int32   `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Uid        int64   `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	PacketLoss float32 `protobuf:"fixed32,5,opt,name=packet_loss,json=packetLoss,proto3" json:"packet_loss,omitempty"`
	Client     string  `protobuf:"bytes,6,opt,name=client,proto3" json:"client,omitempty"`
	Error      *string `protobuf:"bytes,7,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *BotGetIDResponse) Reset() {
	*x = BotGetIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bot_manager_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotGetIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotGetIDResponse) ProtoMessage() {}

func (x *BotGetIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_manager_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotGetIDResponse.ProtoReflect.Descriptor instead.
func (*BotGetIDResponse) Descriptor() ([]byte, []int) {
	return file_bot_manager_proto_rawDescGZIP(), []int{4}
}

func (x *BotGetIDResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BotGetIDResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *BotGetIDResponse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *BotGetIDResponse) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *BotGetIDResponse) GetPacketLoss() float32 {
	if x != nil {
		return x.PacketLoss
	}
	return 0
}

func (x *BotGetIDResponse) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *BotGetIDResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type BotDialogSendRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId  int32  `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Confirm   bool   `protobuf:"varint,2,opt,name=confirm,proto3" json:"confirm,omitempty"`
	ListIndex int32  `protobuf:"varint,3,opt,name=list_index,json=listIndex,proto3" json:"list_index,omitempty"`
	Input     string `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
}

func (x *BotDialogSendRequest) Reset() {
	*x = BotDialogSendRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bot_manager_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotDialogSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotDialogSendRequest) ProtoMessage() {}

func (x *BotDialogSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_manager_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotDialogSendRequest.ProtoReflect.Descriptor instead.
func (*BotDialogSendRequest) Descriptor() ([]byte, []int) {
	return file_bot_manager_proto_rawDescGZIP(), []int{5}
}

func (x *BotDialogSendRequest) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *BotDialogSendRequest) GetConfirm() bool {
	if x != nil {
		return x.Confirm
	}
	return false
}

func (x *BotDialogSendRequest) GetListIndex() int32 {
	if x != nil {
		return x.ListIndex
	}
	return 0
}

func (x *BotDialogSendRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type BotPropsConfirmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId int32 `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	TypeId   int32 `protobuf:"varint,2,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	EstateId int32 `protobuf:"varint,3,opt,name=estate_id,json=estateId,proto3" json:"estate_id,omitempty"`
	Status   bool  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *BotPropsConfirmRequest) Reset() {
	*x = BotPropsConfirmRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bot_manager_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotPropsConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotPropsConfirmRequest) ProtoMessage() {}

func (x *BotPropsConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_manager_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotPropsConfirmRequest.ProtoReflect.Descriptor instead.
func (*BotPropsConfirmRequest) Descriptor() ([]byte, []int) {
	return file_bot_manager_proto_rawDescGZIP(), []int{6}
}

func (x *BotPropsConfirmRequest) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *BotPropsConfirmRequest) GetTypeId() int32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *BotPropsConfirmRequest) GetEstateId() int32 {
	if x != nil {
		return x.EstateId
	}
	return 0
}

func (x *BotPropsConfirmRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type BotPropsConfirmResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EstateId int32  `protobuf:"varint,1,opt,name=estate_id,json=estateId,proto3" json:"estate_id,omitempty"`
	Log      string `protobuf:"bytes,2,opt,name=log,proto3" json:"log,omitempty"`
}

func (x *BotPropsConfirmResponse) Reset() {
	*x = BotPropsConfirmResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bot_manager_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotPropsConfirmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotPropsConfirmResponse) ProtoMessage() {}

func (x *BotPropsConfirmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_manager_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotPropsConfirmResponse.ProtoReflect.Descriptor instead.
func (*BotPropsConfirmResponse) Descriptor() ([]byte, []int) {
	return file_bot_manager_proto_rawDescGZIP(), []int{7}
}

func (x *BotPropsConfirmResponse) GetEstateId() int32 {
	if x != nil {
		return x.EstateId
	}
	return 0
}

func (x *BotPropsConfirmResponse) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

type BotPropsListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId int32 `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
}

func (x *BotPropsListRequest) Reset() {
	*x = BotPropsListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bot_manager_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotPropsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotPropsListRequest) ProtoMessage() {}

func (x *BotPropsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_manager_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotPropsListRequest.ProtoReflect.Descriptor instead.
func (*BotPropsListRequest) Descriptor() ([]byte, []int) {
	return file_bot_manager_proto_rawDescGZIP(), []int{8}
}

func (x *BotPropsListRequest) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

type BotPropsListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Props []*BotPropsListResponseElement `protobuf:"bytes,1,rep,name=props,proto3" json:"props,omitempty"`
}

func (x *BotPropsListResponse) Reset() {
	*x = BotPropsListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bot_manager_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotPropsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotPropsListResponse) ProtoMessage() {}

func (x *BotPropsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_manager_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotPropsListResponse.ProtoReflect.Descriptor instead.
func (*BotPropsListResponse) Descriptor() ([]byte, []int) {
	return file_bot_manager_proto_rawDescGZIP(), []int{9}
}

func (x *BotPropsListResponse) GetProps() []*BotPropsListResponseElement {
	if x != nil {
		return x.Props
	}
	return nil
}

type BotPropsListResponseElement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nickname string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Type     string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	EstateId int32                  `protobuf:"varint,3,opt,name=estate_id,json=estateId,proto3" json:"estate_id,omitempty"`
	Date     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *BotPropsListResponseElement) Reset() {
	*x = BotPropsListResponseElement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bot_manager_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotPropsListResponseElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotPropsListResponseElement) ProtoMessage() {}

func (x *BotPropsListResponseElement) ProtoReflect() protoreflect.Message {
	mi := &file_bot_manager_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotPropsListResponseElement.ProtoReflect.Descriptor instead.
func (*BotPropsListResponseElement) Descriptor() ([]byte, []int) {
	return file_bot_manager_proto_rawDescGZIP(), []int{10}
}

func (x *BotPropsListResponseElement) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *BotPropsListResponseElement) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BotPropsListResponseElement) GetEstateId() int32 {
	if x != nil {
		return x.EstateId
	}
	return 0
}

func (x *BotPropsListResponseElement) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type BotRakBotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId int32  `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Ip       string `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *BotRakBotRequest) Reset() {
	*x = BotRakBotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bot_manager_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotRakBotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotRakBotRequest) ProtoMessage() {}

func (x *BotRakBotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_manager_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotRakBotRequest.ProtoReflect.Descriptor instead.
func (*BotRakBotRequest) Descriptor() ([]byte, []int) {
	return file_bot_manager_proto_rawDescGZIP(), []int{11}
}

func (x *BotRakBotRequest) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *BotRakBotRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *BotRakBotRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type BotRakBotResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success  bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
}

func (x *BotRakBotResponse) Reset() {
	*x = BotRakBotResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bot_manager_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotRakBotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotRakBotResponse) ProtoMessage() {}

func (x *BotRakBotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_manager_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotRakBotResponse.ProtoReflect.Descriptor instead.
func (*BotRakBotResponse) Descriptor() ([]byte, []int) {
	return file_bot_manager_proto_rawDescGZIP(), []int{12}
}

func (x *BotRakBotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BotRakBotResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type SendBotCommandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId int32  `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Command  string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
}

func (x *SendBotCommandRequest) Reset() {
	*x = SendBotCommandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bot_manager_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendBotCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBotCommandRequest) ProtoMessage() {}

func (x *SendBotCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_manager_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBotCommandRequest.ProtoReflect.Descriptor instead.
func (*SendBotCommandRequest) Descriptor() ([]byte, []int) {
	return file_bot_manager_proto_rawDescGZIP(), []int{13}
}

func (x *SendBotCommandRequest) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *SendBotCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type SendBotCommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommandId string `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Success   bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *SendBotCommandResponse) Reset() {
	*x = SendBotCommandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bot_manager_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendBotCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBotCommandResponse) ProtoMessage() {}

func (x *SendBotCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_manager_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBotCommandResponse.ProtoReflect.Descriptor instead.
func (*SendBotCommandResponse) Descriptor() ([]byte, []int) {
	return file_bot_manager_proto_rawDescGZIP(), []int{14}
}

func (x *SendBotCommandResponse) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *SendBotCommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SendBotCommandV2Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId int32  `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Command  string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
}

func (x *SendBotCommandV2Request) Reset() {
	*x = SendBotCommandV2Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bot_manager_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendBotCommandV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBotCommandV2Request) ProtoMessage() {}

func (x *SendBotCommandV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_bot_manager_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBotCommandV2Request.ProtoReflect.Descriptor instead.
func (*SendBotCommandV2Request) Descriptor() ([]byte, []int) {
	return file_bot_manager_proto_rawDescGZIP(), []int{15}
}

func (x *SendBotCommandV2Request) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *SendBotCommandV2Request) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type SendBotCommandV2Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommandId       string  `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	SuccessCommand  bool    `protobuf:"varint,2,opt,name=success_command,json=successCommand,proto3" json:"success_command,omitempty"`
	SuccessGarant   bool    `protobuf:"varint,3,opt,name=success_garant,json=successGarant,proto3" json:"success_garant,omitempty"`
	CommandRequest  string  `protobuf:"bytes,4,opt,name=command_request,json=commandRequest,proto3" json:"command_request,omitempty"`
	CommandResponse string  `protobuf:"bytes,5,opt,name=command_response,json=commandResponse,proto3" json:"command_response,omitempty"`
	Error           *string `protobuf:"bytes,6,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *SendBotCommandV2Response) Reset() {
	*x = SendBotCommandV2Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bot_manager_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendBotCommandV2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBotCommandV2Response) ProtoMessage() {}

func (x *SendBotCommandV2Response) ProtoReflect() protoreflect.Message {
	mi := &file_bot_manager_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBotCommandV2Response.ProtoReflect.Descriptor instead.
func (*SendBotCommandV2Response) Descriptor() ([]byte, []int) {
	return file_bot_manager_proto_rawDescGZIP(), []int{16}
}

func (x *SendBotCommandV2Response) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *SendBotCommandV2Response) GetSuccessCommand() bool {
	if x != nil {
		return x.SuccessCommand
	}
	return false
}

func (x *SendBotCommandV2Response) GetSuccessGarant() bool {
	if x != nil {
		return x.SuccessGarant
	}
	return false
}

func (x *SendBotCommandV2Response) GetCommandRequest() string {
	if x != nil {
		return x.CommandRequest
	}
	return ""
}

func (x *SendBotCommandV2Response) GetCommandResponse() string {
	if x != nil {
		return x.CommandResponse
	}
	return ""
}

func (x *SendBotCommandV2Response) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type BotGetOnlineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId int32  `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
}

func (x *BotGetOnlineRequest) Reset() {
	*x = BotGetOnlineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bot_manager_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotGetOnlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotGetOnlineRequest) ProtoMessage() {}

func (x *BotGetOnlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_manager_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotGetOnlineRequest.ProtoReflect.Descriptor instead.
func (*BotGetOnlineRequest) Descriptor() ([]byte, []int) {
	return file_bot_manager_proto_rawDescGZIP(), []int{17}
}

func (x *BotGetOnlineRequest) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *BotGetOnlineRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type BotGetOnlineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nickname string `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	RegIp    string `protobuf:"bytes,2,opt,name=reg_ip,json=regIp,proto3" json:"reg_ip,omitempty"`
	LastIp   string `protobuf:"bytes,3,opt,name=last_ip,json=lastIp,proto3" json:"last_ip,omitempty"`
}

func (x *BotGetOnlineResponse) Reset() {
	*x = BotGetOnlineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bot_manager_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotGetOnlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotGetOnlineResponse) ProtoMessage() {}

func (x *BotGetOnlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_manager_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotGetOnlineResponse.ProtoReflect.Descriptor instead.
func (*BotGetOnlineResponse) Descriptor() ([]byte, []int) {
	return file_bot_manager_proto_rawDescGZIP(), []int{18}
}

func (x *BotGetOnlineResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *BotGetOnlineResponse) GetRegIp() string {
	if x != nil {
		return x.RegIp
	}
	return ""
}

func (x *BotGetOnlineResponse) GetLastIp() string {
	if x != nil {
		return x.LastIp
	}
	return ""
}

type BotGetOrgMemberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId       int32 `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	OrganizationId int32 `protobuf:"varint,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
}

func (x *BotGetOrgMemberRequest) Reset() {
	*x = BotGetOrgMemberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bot_manager_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotGetOrgMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotGetOrgMemberRequest) ProtoMessage() {}

func (x *BotGetOrgMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_manager_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotGetOrgMemberRequest.ProtoReflect.Descriptor instead.
func (*BotGetOrgMemberRequest) Descriptor() ([]byte, []int) {
	return file_bot_manager_proto_rawDescGZIP(), []int{19}
}

func (x *BotGetOrgMemberRequest) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *BotGetOrgMemberRequest) GetOrganizationId() int32 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

type BotGetOrgMemberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrganizationId   int32  `protobuf:"varint,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	OrganizationName string `protobuf:"bytes,2,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	LeaderName       string `protobuf:"bytes,3,opt,name=leader_name,json=leaderName,proto3" json:"leader_name,omitempty"`
	LeaderId         int32  `protobuf:"varint,4,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	DeputyCount      int32  `protobuf:"varint,5,opt,name=deputy_count,json=deputyCount,proto3" json:"deputy_count,omitempty"`
	MemberCount      int32  `protobuf:"varint,6,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	MemberAfkCount   int32  `protobuf:"varint,7,opt,name=member_afk_count,json=memberAfkCount,proto3" json:"member_afk_count,omitempty"`
	Raw              string `protobuf:"bytes,8,opt,name=raw,proto3" json:"raw,omitempty"`
}

func (x *BotGetOrgMemberResponse) Reset() {
	*x = BotGetOrgMemberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bot_manager_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotGetOrgMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotGetOrgMemberResponse) ProtoMessage() {}

func (x *BotGetOrgMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_manager_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotGetOrgMemberResponse.ProtoReflect.Descriptor instead.
func (*BotGetOrgMemberResponse) Descriptor() ([]byte, []int) {
	return file_bot_manager_proto_rawDescGZIP(), []int{20}
}

func (x *BotGetOrgMemberResponse) GetOrganizationId() int32 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *BotGetOrgMemberResponse) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *BotGetOrgMemberResponse) GetLeaderName() string {
	if x != nil {
		return x.LeaderName
	}
	return ""
}

func (x *BotGetOrgMemberResponse) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *BotGetOrgMemberResponse) GetDeputyCount() int32 {
	if x != nil {
		return x.DeputyCount
	}
	return 0
}

func (x *BotGetOrgMemberResponse) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *BotGetOrgMemberResponse) GetMemberAfkCount() int32 {
	if x != nil {
		return x.MemberAfkCount
	}
	return 0
}

func (x *BotGetOrgMemberResponse) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

var File_bot_manager_proto protoreflect.FileDescriptor

var file_bot_manager_proto_rawDesc = []byte{
	0x0a, 0x11, 0x62, 0x6f, 0x74, 0x2d, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x36, 0x0a, 0x17, 0x42, 0x6f, 0x74, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0x6c, 0x0a, 0x18, 0x42, 0x6f, 0x74,
	0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x42, 0x6f, 0x74, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x67,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a,
	0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xac, 0x02, 0x0a, 0x14, 0x42, 0x6f, 0x74, 0x47,
	0x65, 0x74, 0x4f, 0x72, 0x67, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x27, 0x0a, 0x0f, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6f, 0x72, 0x67, 0x61, 0x6e,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x11, 0x6f, 0x72, 0x67,
	0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6c, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x65, 0x70, 0x75, 0x74, 0x79, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x64, 0x65, 0x70, 0x75,
	0x74, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x28, 0x0a, 0x10, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x5f, 0x61, 0x66, 0x6b, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x41, 0x66, 0x6b, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x61, 0x77, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x72, 0x61, 0x77, 0x22, 0x54, 0x0a, 0x0f, 0x42, 0x6f, 0x74, 0x47, 0x65, 0x74,
	0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x22, 0xc4, 0x01, 0x0a,
	0x10, 0x42, 0x6f, 0x74, 0x47, 0x65, 0x74, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x5f,
	0x6c, 0x6f, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x70, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x4c, 0x6f, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x19,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0x82, 0x01, 0x0a, 0x14, 0x42, 0x6f, 0x74, 0x44, 0x69, 0x61, 0x6c, 0x6f,
	0x67, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x72, 0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x22, 0x83, 0x01, 0x0a, 0x16, 0x42, 0x6f, 0x74,
	0x50, 0x72, 0x6f, 0x70, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x74, 0x79, 0x70, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x65, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x48,
	0x0a, 0x17, 0x42, 0x6f, 0x74, 0x50, 0x72, 0x6f, 0x70, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x65, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6f, 0x67, 0x22, 0x32, 0x0a, 0x13, 0x42, 0x6f, 0x74, 0x50,
	0x72, 0x6f, 0x70, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0x4a, 0x0a, 0x14,
	0x42, 0x6f, 0x74, 0x50, 0x72, 0x6f, 0x70, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x70, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x42, 0x6f, 0x74, 0x50, 0x72, 0x6f, 0x70, 0x73, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x70, 0x73, 0x22, 0x9a, 0x01, 0x0a, 0x1b, 0x42, 0x6f, 0x74,
	0x50, 0x72, 0x6f, 0x70, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x65, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0x5b, 0x0a, 0x10, 0x42, 0x6f, 0x74, 0x52, 0x61, 0x6b, 0x42,
	0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x70, 0x22, 0x49, 0x0a, 0x11, 0x42, 0x6f, 0x74, 0x52, 0x61, 0x6b, 0x42, 0x6f, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4e, 0x0a,
	0x15, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x51, 0x0a,
	0x16, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x22, 0x50, 0x0a, 0x17, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x56, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x22, 0x82, 0x02, 0x0a, 0x18, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x74, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x56, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x27,
	0x0a, 0x0f, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x5f, 0x67, 0x61, 0x72, 0x61, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0d, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x47, 0x61, 0x72, 0x61, 0x6e, 0x74, 0x12, 0x27,
	0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a,
	0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x4e, 0x0a, 0x13, 0x42, 0x6f, 0x74, 0x47, 0x65,
	0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e,
	0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e,
	0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x62, 0x0a, 0x14, 0x42, 0x6f, 0x74, 0x47, 0x65,
	0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x72,
	0x65, 0x67, 0x5f, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x67,
	0x49, 0x70, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x69, 0x70, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x61, 0x73, 0x74, 0x49, 0x70, 0x22, 0x5e, 0x0a, 0x16, 0x42,
	0x6f, 0x74, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6f, 0x72, 0x67,
	0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0xaf, 0x02, 0x0a, 0x17,
	0x42, 0x6f, 0x74, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x6f, 0x72, 0x67, 0x61, 0x6e,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x12, 0x2b, 0x0a, 0x11, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6f, 0x72, 0x67,
	0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x64,
	0x65, 0x70, 0x75, 0x74, 0x79, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x64, 0x65, 0x70, 0x75, 0x74, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x21,
	0x0a, 0x0c, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x28, 0x0a, 0x10, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x61, 0x66, 0x6b, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x41, 0x66, 0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72,
	0x61, 0x77, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x61, 0x77, 0x32, 0xf3, 0x04,
	0x0a, 0x0a, 0x42, 0x6f, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x43, 0x0a, 0x0b,
	0x53, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x16, 0x2e, 0x53, 0x65,
	0x6e, 0x64, 0x42, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x74, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x03, 0x88, 0x02,
	0x01, 0x12, 0x44, 0x0a, 0x0d, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x56, 0x32, 0x12, 0x18, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x56, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x53,
	0x65, 0x6e, 0x64, 0x42, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x56, 0x32, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x4f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x12, 0x14, 0x2e, 0x42, 0x6f, 0x74, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x42, 0x6f, 0x74,
	0x47, 0x65, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x41, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x17, 0x2e, 0x42, 0x6f, 0x74, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x42, 0x6f, 0x74,
	0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x52, 0x61, 0x6b, 0x42, 0x6f, 0x74, 0x12, 0x11,
	0x2e, 0x42, 0x6f, 0x74, 0x52, 0x61, 0x6b, 0x42, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x12, 0x2e, 0x42, 0x6f, 0x74, 0x52, 0x61, 0x6b, 0x42, 0x6f, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x70, 0x73, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x14, 0x2e, 0x42, 0x6f, 0x74, 0x50, 0x72, 0x6f, 0x70, 0x73, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x42, 0x6f, 0x74, 0x50, 0x72,
	0x6f, 0x70, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x41, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x70, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x12,
	0x17, 0x2e, 0x42, 0x6f, 0x74, 0x50, 0x72, 0x6f, 0x70, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x42, 0x6f, 0x74, 0x50, 0x72,
	0x6f, 0x70, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x53, 0x65, 0x6e, 0x64,
	0x12, 0x15, 0x2e, 0x42, 0x6f, 0x74, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x53, 0x65, 0x6e, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12,
	0x2c, 0x0a, 0x05, 0x47, 0x65, 0x74, 0x49, 0x44, 0x12, 0x10, 0x2e, 0x42, 0x6f, 0x74, 0x47, 0x65,
	0x74, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x42, 0x6f, 0x74,
	0x47, 0x65, 0x74, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x18,
	0x2e, 0x42, 0x6f, 0x74, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x42, 0x6f, 0x74, 0x47, 0x65,
	0x74, 0x4f, 0x72, 0x67, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x1a, 0x5a, 0x18, 0x62, 0x6f, 0x74, 0x2d, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x2f, 0x3b, 0x62, 0x6f, 0x74, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bot_manager_proto_rawDescOnce sync.Once
	file_bot_manager_proto_rawDescData = file_bot_manager_proto_rawDesc
)

func file_bot_manager_proto_rawDescGZIP() []byte {
	file_bot_manager_proto_rawDescOnce.Do(func() {
		file_bot_manager_proto_rawDescData = protoimpl.X.CompressGZIP(file_bot_manager_proto_rawDescData)
	})
	return file_bot_manager_proto_rawDescData
}

var file_bot_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_bot_manager_proto_goTypes = []interface{}{
	(*BotGetOrgMembersRequest)(nil),     // 0: BotGetOrgMembersRequest
	(*BotGetOrgMembersResponse)(nil),    // 1: BotGetOrgMembersResponse
	(*BotGetOrgMembersItem)(nil),        // 2: BotGetOrgMembersItem
	(*BotGetIDRequest)(nil),             // 3: BotGetIDRequest
	(*BotGetIDResponse)(nil),            // 4: BotGetIDResponse
	(*BotDialogSendRequest)(nil),        // 5: BotDialogSendRequest
	(*BotPropsConfirmRequest)(nil),      // 6: BotPropsConfirmRequest
	(*BotPropsConfirmResponse)(nil),     // 7: BotPropsConfirmResponse
	(*BotPropsListRequest)(nil),         // 8: BotPropsListRequest
	(*BotPropsListResponse)(nil),        // 9: BotPropsListResponse
	(*BotPropsListResponseElement)(nil), // 10: BotPropsListResponseElement
	(*BotRakBotRequest)(nil),            // 11: BotRakBotRequest
	(*BotRakBotResponse)(nil),           // 12: BotRakBotResponse
	(*SendBotCommandRequest)(nil),       // 13: SendBotCommandRequest
	(*SendBotCommandResponse)(nil),      // 14: SendBotCommandResponse
	(*SendBotCommandV2Request)(nil),     // 15: SendBotCommandV2Request
	(*SendBotCommandV2Response)(nil),    // 16: SendBotCommandV2Response
	(*BotGetOnlineRequest)(nil),         // 17: BotGetOnlineRequest
	(*BotGetOnlineResponse)(nil),        // 18: BotGetOnlineResponse
	(*BotGetOrgMemberRequest)(nil),      // 19: BotGetOrgMemberRequest
	(*BotGetOrgMemberResponse)(nil),     // 20: BotGetOrgMemberResponse
	(*timestamppb.Timestamp)(nil),       // 21: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),               // 22: google.protobuf.Empty
}
var file_bot_manager_proto_depIdxs = []int32{
	2,  // 0: BotGetOrgMembersResponse.items:type_name -> BotGetOrgMembersItem
	10, // 1: BotPropsListResponse.props:type_name -> BotPropsListResponseElement
	21, // 2: BotPropsListResponseElement.date:type_name -> google.protobuf.Timestamp
	13, // 3: BotManager.SendCommand:input_type -> SendBotCommandRequest
	15, // 4: BotManager.SendCommandV2:input_type -> SendBotCommandV2Request
	17, // 5: BotManager.GetOnline:input_type -> BotGetOnlineRequest
	19, // 6: BotManager.GetOrgMember:input_type -> BotGetOrgMemberRequest
	11, // 7: BotManager.RakBot:input_type -> BotRakBotRequest
	8,  // 8: BotManager.PropsList:input_type -> BotPropsListRequest
	6,  // 9: BotManager.PropsConfirm:input_type -> BotPropsConfirmRequest
	5,  // 10: BotManager.DialogSend:input_type -> BotDialogSendRequest
	3,  // 11: BotManager.GetID:input_type -> BotGetIDRequest
	0,  // 12: BotManager.GetOrgMembers:input_type -> BotGetOrgMembersRequest
	14, // 13: BotManager.SendCommand:output_type -> SendBotCommandResponse
	16, // 14: BotManager.SendCommandV2:output_type -> SendBotCommandV2Response
	18, // 15: BotManager.GetOnline:output_type -> BotGetOnlineResponse
	20, // 16: BotManager.GetOrgMember:output_type -> BotGetOrgMemberResponse
	12, // 17: BotManager.RakBot:output_type -> BotRakBotResponse
	9,  // 18: BotManager.PropsList:output_type -> BotPropsListResponse
	7,  // 19: BotManager.PropsConfirm:output_type -> BotPropsConfirmResponse
	22, // 20: BotManager.DialogSend:output_type -> google.protobuf.Empty
	4,  // 21: BotManager.GetID:output_type -> BotGetIDResponse
	1,  // 22: BotManager.GetOrgMembers:output_type -> BotGetOrgMembersResponse
	13, // [13:23] is the sub-list for method output_type
	3,  // [3:13] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_bot_manager_proto_init() }
func file_bot_manager_proto_init() {
	if File_bot_manager_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bot_manager_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotGetOrgMembersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bot_manager_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotGetOrgMembersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bot_manager_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotGetOrgMembersItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bot_manager_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotGetIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bot_manager_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotGetIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bot_manager_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotDialogSendRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bot_manager_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotPropsConfirmRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bot_manager_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotPropsConfirmResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bot_manager_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotPropsListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bot_manager_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotPropsListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bot_manager_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotPropsListResponseElement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bot_manager_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotRakBotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bot_manager_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotRakBotResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bot_manager_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendBotCommandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bot_manager_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendBotCommandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bot_manager_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendBotCommandV2Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bot_manager_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendBotCommandV2Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bot_manager_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotGetOnlineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bot_manager_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotGetOnlineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bot_manager_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotGetOrgMemberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bot_manager_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotGetOrgMemberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_bot_manager_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_bot_manager_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_bot_manager_proto_msgTypes[16].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bot_manager_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bot_manager_proto_goTypes,
		DependencyIndexes: file_bot_manager_proto_depIdxs,
		MessageInfos:      file_bot_manager_proto_msgTypes,
	}.Build()
	File_bot_manager_proto = out.File
	file_bot_manager_proto_rawDesc = nil
	file_bot_manager_proto_goTypes = nil
	file_bot_manager_proto_depIdxs = nil
}
