// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: id.proto

package id

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MappingSource int32

const (
	MappingSource_discord MappingSource = 0
	MappingSource_grafana MappingSource = 1
	MappingSource_leader  MappingSource = 2
)

// Enum value maps for MappingSource.
var (
	MappingSource_name = map[int32]string{
		0: "discord",
		1: "grafana",
		2: "leader",
	}
	MappingSource_value = map[string]int32{
		"discord": 0,
		"grafana": 1,
		"leader":  2,
	}
)

func (x MappingSource) Enum() *MappingSource {
	p := new(MappingSource)
	*p = x
	return p
}

func (x MappingSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MappingSource) Descriptor() protoreflect.EnumDescriptor {
	return file_id_proto_enumTypes[0].Descriptor()
}

func (MappingSource) Type() protoreflect.EnumType {
	return &file_id_proto_enumTypes[0]
}

func (x MappingSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MappingSource.Descriptor instead.
func (MappingSource) EnumDescriptor() ([]byte, []int) {
	return file_id_proto_rawDescGZIP(), []int{0}
}

type Mapping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source  MappingSource `protobuf:"varint,1,opt,name=source,proto3,enum=MappingSource" json:"source,omitempty"`
	UserIdA string        `protobuf:"bytes,2,opt,name=user_id_a,json=userIdA,proto3" json:"user_id_a,omitempty"`
	UserIdB *int32        `protobuf:"varint,3,opt,name=user_id_b,json=userIdB,proto3,oneof" json:"user_id_b,omitempty"`
	UserIdC *string       `protobuf:"bytes,4,opt,name=user_id_c,json=userIdC,proto3,oneof" json:"user_id_c,omitempty"`
	Data    []byte        `protobuf:"bytes,5,opt,name=data,proto3,oneof" json:"data,omitempty"`
}

func (x *Mapping) Reset() {
	*x = Mapping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_id_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mapping) ProtoMessage() {}

func (x *Mapping) ProtoReflect() protoreflect.Message {
	mi := &file_id_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mapping.ProtoReflect.Descriptor instead.
func (*Mapping) Descriptor() ([]byte, []int) {
	return file_id_proto_rawDescGZIP(), []int{0}
}

func (x *Mapping) GetSource() MappingSource {
	if x != nil {
		return x.Source
	}
	return MappingSource_discord
}

func (x *Mapping) GetUserIdA() string {
	if x != nil {
		return x.UserIdA
	}
	return ""
}

func (x *Mapping) GetUserIdB() int32 {
	if x != nil && x.UserIdB != nil {
		return *x.UserIdB
	}
	return 0
}

func (x *Mapping) GetUserIdC() string {
	if x != nil && x.UserIdC != nil {
		return *x.UserIdC
	}
	return ""
}

func (x *Mapping) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type MappingBySourceAndUserIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source MappingSource `protobuf:"varint,1,opt,name=source,proto3,enum=MappingSource" json:"source,omitempty"`
	UserId string        `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *MappingBySourceAndUserIDRequest) Reset() {
	*x = MappingBySourceAndUserIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_id_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MappingBySourceAndUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappingBySourceAndUserIDRequest) ProtoMessage() {}

func (x *MappingBySourceAndUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_id_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappingBySourceAndUserIDRequest.ProtoReflect.Descriptor instead.
func (*MappingBySourceAndUserIDRequest) Descriptor() ([]byte, []int) {
	return file_id_proto_rawDescGZIP(), []int{1}
}

func (x *MappingBySourceAndUserIDRequest) GetSource() MappingSource {
	if x != nil {
		return x.Source
	}
	return MappingSource_discord
}

func (x *MappingBySourceAndUserIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type MappingBySourceAndUserIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mapping []*Mapping `protobuf:"bytes,1,rep,name=mapping,proto3" json:"mapping,omitempty"`
}

func (x *MappingBySourceAndUserIDResponse) Reset() {
	*x = MappingBySourceAndUserIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_id_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MappingBySourceAndUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappingBySourceAndUserIDResponse) ProtoMessage() {}

func (x *MappingBySourceAndUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_id_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappingBySourceAndUserIDResponse.ProtoReflect.Descriptor instead.
func (*MappingBySourceAndUserIDResponse) Descriptor() ([]byte, []int) {
	return file_id_proto_rawDescGZIP(), []int{2}
}

func (x *MappingBySourceAndUserIDResponse) GetMapping() []*Mapping {
	if x != nil {
		return x.Mapping
	}
	return nil
}

type UserIDByCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source MappingSource `protobuf:"varint,1,opt,name=source,proto3,enum=MappingSource" json:"source,omitempty"`
	Code   string        `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *UserIDByCodeRequest) Reset() {
	*x = UserIDByCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_id_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserIDByCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDByCodeRequest) ProtoMessage() {}

func (x *UserIDByCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_id_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDByCodeRequest.ProtoReflect.Descriptor instead.
func (*UserIDByCodeRequest) Descriptor() ([]byte, []int) {
	return file_id_proto_rawDescGZIP(), []int{3}
}

func (x *UserIDByCodeRequest) GetSource() MappingSource {
	if x != nil {
		return x.Source
	}
	return MappingSource_discord
}

func (x *UserIDByCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type UserIDByCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UserIDByCodeResponse) Reset() {
	*x = UserIDByCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_id_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserIDByCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDByCodeResponse) ProtoMessage() {}

func (x *UserIDByCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_id_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDByCodeResponse.ProtoReflect.Descriptor instead.
func (*UserIDByCodeResponse) Descriptor() ([]byte, []int) {
	return file_id_proto_rawDescGZIP(), []int{4}
}

func (x *UserIDByCodeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserIDUserByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UserIDUserByIDRequest) Reset() {
	*x = UserIDUserByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_id_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserIDUserByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDUserByIDRequest) ProtoMessage() {}

func (x *UserIDUserByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_id_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDUserByIDRequest.ProtoReflect.Descriptor instead.
func (*UserIDUserByIDRequest) Descriptor() ([]byte, []int) {
	return file_id_proto_rawDescGZIP(), []int{5}
}

func (x *UserIDUserByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserIDUserByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *UserIDUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *UserIDUserByIDResponse) Reset() {
	*x = UserIDUserByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_id_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserIDUserByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDUserByIDResponse) ProtoMessage() {}

func (x *UserIDUserByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_id_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDUserByIDResponse.ProtoReflect.Descriptor instead.
func (*UserIDUserByIDResponse) Descriptor() ([]byte, []int) {
	return file_id_proto_rawDescGZIP(), []int{6}
}

func (x *UserIDUserByIDResponse) GetUser() *UserIDUser {
	if x != nil {
		return x.User
	}
	return nil
}

type UserIDUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email      string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	GivenName  string `protobuf:"bytes,4,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	FamilyName string `protobuf:"bytes,5,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
}

func (x *UserIDUser) Reset() {
	*x = UserIDUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_id_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserIDUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDUser) ProtoMessage() {}

func (x *UserIDUser) ProtoReflect() protoreflect.Message {
	mi := &file_id_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDUser.ProtoReflect.Descriptor instead.
func (*UserIDUser) Descriptor() ([]byte, []int) {
	return file_id_proto_rawDescGZIP(), []int{7}
}

func (x *UserIDUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserIDUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserIDUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserIDUser) GetGivenName() string {
	if x != nil {
		return x.GivenName
	}
	return ""
}

func (x *UserIDUser) GetFamilyName() string {
	if x != nil {
		return x.FamilyName
	}
	return ""
}

var File_id_proto protoreflect.FileDescriptor

var file_id_proto_rawDesc = []byte{
	0x0a, 0x08, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcd, 0x01, 0x0a, 0x07, 0x4d, 0x61, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x09, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x5f, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x41, 0x12, 0x1f, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x5f, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x42, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x5f, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x43, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x02, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x88,
	0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x5f, 0x62,
	0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x5f, 0x63, 0x42, 0x07,
	0x0a, 0x05, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x22, 0x62, 0x0a, 0x1f, 0x4d, 0x61, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x42, 0x79, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x41, 0x6e, 0x64, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x4d, 0x61, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x46, 0x0a, 0x20, 0x4d,
	0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x42, 0x79, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x41, 0x6e,
	0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x22, 0x0a, 0x07, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x07, 0x6d, 0x61, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x22, 0x51, 0x0a, 0x13, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x42, 0x79, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x4d, 0x61, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x26, 0x0a, 0x14, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x42, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x27,
	0x0a, 0x15, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x39, 0x0a, 0x16, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1f, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x22, 0x86, 0x01, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x67,
	0x69, 0x76, 0x65, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x67, 0x69, 0x76, 0x65, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x61,
	0x6d, 0x69, 0x6c, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x2a, 0x35, 0x0a, 0x0d, 0x4d,
	0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x0b, 0x0a, 0x07,
	0x64, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x64, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x67, 0x72, 0x61,
	0x66, 0x61, 0x6e, 0x61, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x10, 0x02, 0x32, 0x97, 0x02, 0x0a, 0x0e, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5f, 0x0a, 0x18, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67,
	0x42, 0x79, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x41, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x20, 0x2e, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x42, 0x79, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x41, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x42, 0x79, 0x53,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x41, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x12, 0x08, 0x2e, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x12, 0x3b, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x42, 0x79, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x14, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x42, 0x79, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x42, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3b, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x12, 0x16, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x55, 0x73, 0x65, 0x72,
	0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x5a, 0x06,
	0x69, 0x64, 0x2f, 0x3b, 0x69, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_id_proto_rawDescOnce sync.Once
	file_id_proto_rawDescData = file_id_proto_rawDesc
)

func file_id_proto_rawDescGZIP() []byte {
	file_id_proto_rawDescOnce.Do(func() {
		file_id_proto_rawDescData = protoimpl.X.CompressGZIP(file_id_proto_rawDescData)
	})
	return file_id_proto_rawDescData
}

var file_id_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_id_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_id_proto_goTypes = []interface{}{
	(MappingSource)(0),                       // 0: MappingSource
	(*Mapping)(nil),                          // 1: Mapping
	(*MappingBySourceAndUserIDRequest)(nil),  // 2: MappingBySourceAndUserIDRequest
	(*MappingBySourceAndUserIDResponse)(nil), // 3: MappingBySourceAndUserIDResponse
	(*UserIDByCodeRequest)(nil),              // 4: UserIDByCodeRequest
	(*UserIDByCodeResponse)(nil),             // 5: UserIDByCodeResponse
	(*UserIDUserByIDRequest)(nil),            // 6: UserIDUserByIDRequest
	(*UserIDUserByIDResponse)(nil),           // 7: UserIDUserByIDResponse
	(*UserIDUser)(nil),                       // 8: UserIDUser
	(*emptypb.Empty)(nil),                    // 9: google.protobuf.Empty
}
var file_id_proto_depIdxs = []int32{
	0, // 0: Mapping.source:type_name -> MappingSource
	0, // 1: MappingBySourceAndUserIDRequest.source:type_name -> MappingSource
	1, // 2: MappingBySourceAndUserIDResponse.mapping:type_name -> Mapping
	0, // 3: UserIDByCodeRequest.source:type_name -> MappingSource
	8, // 4: UserIDUserByIDResponse.user:type_name -> UserIDUser
	2, // 5: MappingService.MappingBySourceAndUserID:input_type -> MappingBySourceAndUserIDRequest
	1, // 6: MappingService.Create:input_type -> Mapping
	4, // 7: MappingService.UserIDByCode:input_type -> UserIDByCodeRequest
	6, // 8: MappingService.UserByID:input_type -> UserIDUserByIDRequest
	3, // 9: MappingService.MappingBySourceAndUserID:output_type -> MappingBySourceAndUserIDResponse
	9, // 10: MappingService.Create:output_type -> google.protobuf.Empty
	5, // 11: MappingService.UserIDByCode:output_type -> UserIDByCodeResponse
	7, // 12: MappingService.UserByID:output_type -> UserIDUserByIDResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_id_proto_init() }
func file_id_proto_init() {
	if File_id_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_id_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mapping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_id_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MappingBySourceAndUserIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_id_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MappingBySourceAndUserIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_id_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserIDByCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_id_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserIDByCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_id_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserIDUserByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_id_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserIDUserByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_id_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserIDUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_id_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_id_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_id_proto_goTypes,
		DependencyIndexes: file_id_proto_depIdxs,
		EnumInfos:         file_id_proto_enumTypes,
		MessageInfos:      file_id_proto_msgTypes,
	}.Build()
	File_id_proto = out.File
	file_id_proto_rawDesc = nil
	file_id_proto_goTypes = nil
	file_id_proto_depIdxs = nil
}
