// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: id.proto

package id

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MappingServiceClient is the client API for MappingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MappingServiceClient interface {
	MappingBySourceAndUserID(ctx context.Context, in *MappingBySourceAndUserIDRequest, opts ...grpc.CallOption) (*MappingBySourceAndUserIDResponse, error)
	Create(ctx context.Context, in *Mapping, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type mappingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMappingServiceClient(cc grpc.ClientConnInterface) MappingServiceClient {
	return &mappingServiceClient{cc}
}

func (c *mappingServiceClient) MappingBySourceAndUserID(ctx context.Context, in *MappingBySourceAndUserIDRequest, opts ...grpc.CallOption) (*MappingBySourceAndUserIDResponse, error) {
	out := new(MappingBySourceAndUserIDResponse)
	err := c.cc.Invoke(ctx, "/MappingService/MappingBySourceAndUserID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mappingServiceClient) Create(ctx context.Context, in *Mapping, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/MappingService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MappingServiceServer is the server API for MappingService service.
// All implementations should embed UnimplementedMappingServiceServer
// for forward compatibility
type MappingServiceServer interface {
	MappingBySourceAndUserID(context.Context, *MappingBySourceAndUserIDRequest) (*MappingBySourceAndUserIDResponse, error)
	Create(context.Context, *Mapping) (*emptypb.Empty, error)
}

// UnimplementedMappingServiceServer should be embedded to have forward compatible implementations.
type UnimplementedMappingServiceServer struct {
}

func (UnimplementedMappingServiceServer) MappingBySourceAndUserID(context.Context, *MappingBySourceAndUserIDRequest) (*MappingBySourceAndUserIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MappingBySourceAndUserID not implemented")
}
func (UnimplementedMappingServiceServer) Create(context.Context, *Mapping) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

// UnsafeMappingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MappingServiceServer will
// result in compilation errors.
type UnsafeMappingServiceServer interface {
	mustEmbedUnimplementedMappingServiceServer()
}

func RegisterMappingServiceServer(s grpc.ServiceRegistrar, srv MappingServiceServer) {
	s.RegisterService(&MappingService_ServiceDesc, srv)
}

func _MappingService_MappingBySourceAndUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MappingBySourceAndUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MappingServiceServer).MappingBySourceAndUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MappingService/MappingBySourceAndUserID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MappingServiceServer).MappingBySourceAndUserID(ctx, req.(*MappingBySourceAndUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MappingService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Mapping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MappingServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MappingService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MappingServiceServer).Create(ctx, req.(*Mapping))
	}
	return interceptor(ctx, in, info, handler)
}

// MappingService_ServiceDesc is the grpc.ServiceDesc for MappingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MappingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MappingService",
	HandlerType: (*MappingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MappingBySourceAndUserID",
			Handler:    _MappingService_MappingBySourceAndUserID_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _MappingService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "id.proto",
}
